name: "News-Ingestion"

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  ingest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install requests
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      - name: Run news_ingest.py
        env:
          FINNHUB_API_KEY: ${{ secrets.FINNHUB_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python backend/news_ingest.py

      - name: Commit & push updated CSV
        env:
          GITHUB_TOKEN: ${{ secrets.INSIGHTFUNDAMENTAL_PAT }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add frontend/data/news_analysis_results.csv
          if git diff --staged --quiet; then
             echo "No changes to commit"
          else
            git commit -m "chore: hourly news ingestion"
            git push
          fi
