# .github/workflows/news_ingest.yml
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: 📰 News-Ingestion

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  ingest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

            - name: Install dependencies
        run: |
          pip install --upgrade pip
          # Stelle sicher, dass requests immer installiert wird
          pip install requests
          # Installiere zusätzliche Pakete aus requirements.txt (falls vorhanden)
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      - name: Run news_ingest.py
        env:
          FINNHUB_API_KEY: ${{ secrets.FINNHUB_API_KEY }}
        run: python backend/news_ingest.py

      - name: Commit & push updated CSV
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          # hier dein Fine-grained Personal Access Token
          github_token: ${{ secrets.INSIGHTFUNDAMENTAL_PAT }}
          commit_message: "chore: hourly news ingestion"
          file_pattern: "frontend/data/news_analysis_results.csv"
