name: "News-Ingestion"

on:
  schedule:
    - cron: '0 * * * *'  # Jede volle Stunde
  workflow_dispatch:

jobs:
  ingest_news:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}  # Personal Access Token mit "repo"-Rechten

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install requests python-dotenv openai
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      - name: Run news_ingest.py
        env:
          FINNHUB_API_KEY: ${{ secrets.FINNHUB_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          echo "Starting news ingestion..."
          python backend/news_ingest.py
          echo "News ingestion completed"

      - name: Commit and push updated CSV
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "github-actions[bot]"

          git add data/news_analysis_results.csv
          git commit -m "chore: hourly news ingestion - $(date -u +'%Y-%m-%d %H:%M:%S UTC')" || echo "Nothing to commit"
          git push origin HEAD:main
